### ISSUE TITLE
Prove AES256Equivalence Axiom key_expand_equiv

### ISSUE THREAD

**Issue by smore-lore** [project-oak/silveroak#590]
I noticed we don't have this, while trying to port proofs over to know sequential circuit setup.

Are there any other axioms we need to finalize phase I?

**Comment by jadephilipoom** [comment]
Phase 1 intentionally excludes key expansion (see the description on the project: "minus key expansion"); the axiom is expected to remain. We decided at the start of phase 1 to narrow the scope as much as possible, and since key expansion is relatively separate from the rest of the cipher (and also an "optional" part of a hardware AES block --  see discussion [here](https://docs.opentitan.org/hw/ip/aes/doc/) under "Datapath Architecture and Operation"). It may seem counter-intuitive to leave out key expansion, but the goal here isn't to produce a production-ready system; we just want a case study for our methodology.
