### ISSUE TITLE
Polish encoder/decoder for core library

### ISSUE THREAD

**Issue by jadephilipoom** [project-oak/silveroak#719]
In #716, the decoder proofs were added to our core `Cava.CavaProperties` export (transitively from `LibProperties`)-- thanks Anish! However, now that they're in the core library, I think it would be good to make some finishing touches to these. In particular:

- If the proofs are exported from `Lib/LibProperties.v`, the corresponding definitions should also be exported from `Lib/Lib.v`
- I'm not sure that `vecConstEq` should be in the core library, since it's more or less a specialization of `eqb` and might make the API more confusing; is it possible to write the decoder without it?
- Some of the lemmas in `DecoderProperties.v` are not specific to the decoder and may belong in the `Util/` folder instead (e.g. `iffb`, `fold_units`)
- Some of the proofs refer to autogenerated names (e.g. `H`, `H0`), which is against our style guide; these should be changed to avoid the autogenerated names

**Comment by atondwal** [comment]
We can move `fold_units` and the other fold lemmas to `Util/` if it ends up being useful for some other proofs, but I tried to rewrite it to be less tied to the implementation of `decoder` today (i.e. use `forall v, InV v vec -> v = unit \/ v =a` instead of mapping a decider over the list), and it makes the whole thing much more complex. If that specific pattern shows up again, it might be worth lifting it out to `Util`, but I'm not sure if we're going to see that exact code again. We might need similar lemmas for LUTs but I'm pretty sure if I try to anticipate which ways to generalize the fold lemmas ahead of time, I'm probably going to get the wrong thing.

So currently my position is that the fold lemmas are pretty specific to `decoder`, but should be good to refer to when we want slightly more general forms of these lemmas for more complex circuits (at which point we might want to replace these).
